server.port=8080
spring.mongodb.uri=mongodb+srv://deepiroot:Deepi21@cluster0.ugwwatx.mongodb.net/solvestack?retryWrites=true&w=majority&tlsAllowInvalidCertificates=true
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.solvestack=DEBUG
spring.jackson.time-zone=UTC
spring.jackson.default-property-inclusion=non_null

